<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SQL Quick Reference Library</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="!RefLibraryFor_SQL__files/libs/clipboard/clipboard.min.js"></script>
<script src="!RefLibraryFor_SQL__files/libs/quarto-html/quarto.js"></script>
<script src="!RefLibraryFor_SQL__files/libs/quarto-html/popper.min.js"></script>
<script src="!RefLibraryFor_SQL__files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="!RefLibraryFor_SQL__files/libs/quarto-html/anchor.min.js"></script>
<link href="!RefLibraryFor_SQL__files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="!RefLibraryFor_SQL__files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="!RefLibraryFor_SQL__files/libs/bootstrap/bootstrap.min.js"></script>
<link href="!RefLibraryFor_SQL__files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="!RefLibraryFor_SQL__files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SQL Quick Reference Library</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sql-quick-reference-materials-from-w3schools" class="level1">
<h1>SQL Quick Reference Materials from W3Schools</h1>
<p>Many of the original materials for this quick reference library were borrowed from W3Schools and the Google Data Analytics Certification through Coursera. However, after coding SQL for over a year and building hundreds of scripts and thousands of lines of code, and working through ChatGPT to build ideas for unique solutions, this codebase can no longer be considered to have one source. I share it freely, I hope it helps.</p>
<p>Darrell Wolfe, Business Intelligence Analyst (BIA) 08/14/2024</p>
<hr>
<section id="useful-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="useful-comparisons">Useful Comparisons</h2>
<p>From Mike Dunn at XTR: I was talking about the EXCEPT “SET” command This compares two columns in the CADINV table for the annual roll for years 2021 and 2022 You can compare any table in multiple databases, but the number of columns has to be identical.</p>
<p>This will show ALL PIN, AIN that exists in 2021 that DO NOT exist in 2022</p>
<p>```{sql eval=FALSE, include=TRUE} select ci.PIN, ci.AIN from CADInv ci where year(ci.InvEffDate) = 2021 and RollCaste = 16001 – ANNUAL group by ci.PIN, ci.AIN</p>
<p>EXCEPT</p>
<p>select ci.PIN, ci.AIN from CADInv ci where year(ci.InvEffDate) = 2022 and RollCaste = 16001 – ANNUAL group by ci.PIN, ci.AIN</p>
</section>
</section>
<section id="this-will-show-all-pin-ain-that-exists-in-2021-that-do-not-exist-in-2022" class="level1">
<h1>This will show ALL PIN, AIN that exists in 2021 that DO NOT exist in 2022</h1>
<pre><code>


You can flip this:
and it shoes al PIN, AIN in 2022 and NOT in 2021



```{sql eval=FALSE, include=TRUE}

select ci.PIN, ci.AIN 
from CADInv ci
where year(ci.InvEffDate) = 2022
and RollCaste = 16001 -- ANNUAL
group by ci.PIN, ci.AIN

EXCEPT

select ci.PIN, ci.AIN 
from CADInv ci
where year(ci.InvEffDate) = 2021
and RollCaste = 16001 -- ANNUAL
group by ci.PIN, ci.AIN


# and it shoes al PIN, AIN in 2022 and NOT in 2021
</code></pre>
<p>the opposite on EXCEPT is INTERSECT</p>
<p>```{sql eval=FALSE, include=TRUE} select ci.PIN, ci.AIN from CADInv ci where year(ci.InvEffDate) = 2022 and RollCaste = 16001 – ANNUAL group by ci.PIN, ci.AIN</p>
<p>INTERSECT</p>
<p>select ci.PIN, ci.AIN from CADInv ci where year(ci.InvEffDate) = 2021 and RollCaste = 16001 – ANNUAL group by ci.PIN, ci.AIN</p>
<pre><code>






------------------------------------------------------------------------

## Most Common Errors

### Joins

#### Improvements of any kind, must filter with Extensions

If you pull improvements or dwellings without an INNER join on extensions, you will get voided records in your results even if it is otherwise filtered for ACTIVE. You must join extensions on lrsn and on extensions to either of these tables (and probably any other table that has extensions on it)



```{sql eval=FALSE, include=TRUE}


From improvements AS i
  Join extensions AS e
  On e.lrsn = i.lrsn
  And e.extension = i.extension
  And e.status = 'A'

FROM dwellings AS d
  Join extensions AS e
  On e.lrsn = d.lrsn
  And e.extension = d.extension
  And e.status = 'A'

</code></pre>
<section id="commas-missing-or-incorrect-placement" class="level3">
<h3 class="anchored" data-anchor-id="commas-missing-or-incorrect-placement">Commas: Missing or Incorrect Placement</h3>
<p>Started using commas behind the select list items</p>
</section>
<section id="with" class="level3">
<h3 class="anchored" data-anchor-id="with">WITH</h3>
<p>CTE Either WITH is missing, or there is an extra WITH</p>
</section>
<section id="cte-in-tableau" class="level3">
<h3 class="anchored" data-anchor-id="cte-in-tableau">CTE in Tableau</h3>
<p>Common table expressions (CTEs) are useful when using “Custom SQL” as a data source in Tableau. CTEs make SQL code more readable, especially for more complex SQL statements. However, Tableau does not support CTEs in “Custom SQL”. Instead, you can use CTEs in “Initial SQL”. To use CTEs in Tableau, you can: Select Data &gt; New Data Source and choose your data source. In the Server Connection dialog box, choose Initial SQL. Enter your CTE in the Initial SQL field. Create a Custom SQL query that selects from the temp table you inserted the records into.</p>
<p>Common Table Expressions (CTEs) are named temporary result sets that are used to manipulate complex sub-query data. CTEs are often preferred over temporary tables when you need to simplify complex queries and improve query readability. CTEs can only be used in the current query scope. Temporary tables are physically created in the tempdb database and can exist for the entire duration of the session. You can use temporary tables when the number of steps needed to solve the problem gets high, or when dealing with really large data sets.</p>
<p>To use CTEs in Tableau, you can: In the Data Source page, click on the caret icon by your current connection and click</p>
<p>Initial SQL.</p>
<p>Add a Custom SQL Query and enter the following:</p>
<p>INTO #temptable</p>
<p>SELECT * FROM #temptable</p>
<p>Tableau does not support CTE expressions in “Custom SQL”.</p>
<hr>
</section>
<section id="most-common-references" class="level2">
<h2 class="anchored" data-anchor-id="most-common-references">Most Common References</h2>
</section>
<section id="declare-variables" class="level2">
<h2 class="anchored" data-anchor-id="declare-variables">Declare Variables</h2>
<p>```{sql eval=FALSE, include=TRUE}</p>
<p>DECLARE <span class="citation" data-cites="TaxYear">@TaxYear</span> INT; SET <span class="citation" data-cites="TaxYear">@TaxYear</span> = YEAR(GETDATE()); – You can use <span class="citation" data-cites="TaxYear">@TaxYear</span> in your queries below /<em> SET <span class="citation" data-cites="TaxYear">@TaxYear</span> = CASE WHEN MONTH(GETDATE()) &gt;= 6 THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()) - 1 END; </em>/</p>
<pre><code>



## Handling Dates



```{sql eval=FALSE, include=TRUE}
f.date_completed AS DateCompleted
,YEAR(f.date_completed) AS Compl_Year
,MONTH(f.date_completed) AS Compl_Month
,DAY(f.date_completed) AS Compl_Day
,DATENAME(MONTH, f.date_completed) AS Compl_MonthName</code></pre>
<p>```{sql eval=FALSE, include=TRUE}</p>
<p>–Declare <span class="citation" data-cites="Year">@Year</span> int = 2024; – Input THIS year here DECLARE <span class="citation" data-cites="TaxYear">@TaxYear</span> INT; SET <span class="citation" data-cites="TaxYear">@TaxYear</span> = YEAR(GETDATE());</p>
<p>–OR –Declare <span class="citation" data-cites="Year">@Year</span> int = 2024; – Input THIS year here</p>
<p>Declare <span class="citation" data-cites="YearPrev">@YearPrev</span> int = <span class="citation" data-cites="Year">@Year</span> - 1; – Input the year here Declare <span class="citation" data-cites="YearPrev2">@YearPrev2</span> int = <span class="citation" data-cites="Year">@Year</span> - 2; – Input the year here Declare <span class="citation" data-cites="YearPrev3">@YearPrev3</span> int = <span class="citation" data-cites="Year">@Year</span> - 3; – Input the year here Declare <span class="citation" data-cites="YearPrev4">@YearPrev4</span> int = <span class="citation" data-cites="Year">@Year</span> - 4; – Input the year here Declare <span class="citation" data-cites="YearPrev5">@YearPrev5</span> int = <span class="citation" data-cites="Year">@Year</span> - 5; – Input the year here</p>
<p>Declare <span class="citation" data-cites="EffYear0101Current">@EffYear0101Current</span> varchar(8) = Cast(<span class="citation" data-cites="Year">@Year</span> as varchar) + ‘0101’; – Generates ‘20230101’ for the previous year Declare <span class="citation" data-cites="EffYear0101Previous">@EffYear0101Previous</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev">@YearPrev</span> as varchar) + ‘0101’; – Generates ‘20230101’ for the previous year Declare <span class="citation" data-cites="EffYear0101Previous2">@EffYear0101Previous2</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev2">@YearPrev2</span> as varchar) + ‘0101’; – Generates ‘20230101’ for the previous year Declare <span class="citation" data-cites="EffYear0101Previous3">@EffYear0101Previous3</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev3">@YearPrev3</span> as varchar) + ‘0101’; – Generates ‘20230101’ for the previous year Declare <span class="citation" data-cites="EffYear0101Previous4">@EffYear0101Previous4</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev4">@YearPrev4</span> as varchar) + ‘0101’; – Generates ‘20230101’ for the previous year Declare <span class="citation" data-cites="EffYear0101Previous5">@EffYear0101Previous5</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev5">@YearPrev5</span> as varchar) + ‘0101’; – Generates ‘20230101’ for the previous year</p>
<p>Declare <span class="citation" data-cites="ValEffDateCurrent">@ValEffDateCurrent</span> date = CAST(CAST(<span class="citation" data-cites="Year">@Year</span> as varchar) + ‘-01-01’ AS DATE); – Generates ‘2023-01-01’ for the current year Declare <span class="citation" data-cites="ValEffDatePrevious">@ValEffDatePrevious</span> date = CAST(CAST(<span class="citation" data-cites="YearPrev">@YearPrev</span> as varchar) + ‘-01-01’ AS DATE); – Generates ‘2022-01-01’ for the previous year Declare <span class="citation" data-cites="ValEffDatePrevious2">@ValEffDatePrevious2</span> date = CAST(CAST(<span class="citation" data-cites="YearPrev2">@YearPrev2</span> as varchar) + ‘-01-01’ AS DATE); – Generates ‘2022-01-01’ for the previous year Declare <span class="citation" data-cites="ValEffDatePrevious3">@ValEffDatePrevious3</span> date = CAST(CAST(<span class="citation" data-cites="YearPrev3">@YearPrev3</span> as varchar) + ‘-01-01’ AS DATE); – Generates ‘2022-01-01’ for the previous year Declare <span class="citation" data-cites="ValEffDatePrevious4">@ValEffDatePrevious4</span> date = CAST(CAST(<span class="citation" data-cites="YearPrev4">@YearPrev4</span> as varchar) + ‘-01-01’ AS DATE); – Generates ‘2022-01-01’ for the previous year Declare <span class="citation" data-cites="ValEffDatePrevious5">@ValEffDatePrevious5</span> date = CAST(CAST(<span class="citation" data-cites="YearPrev5">@YearPrev5</span> as varchar) + ‘-01-01’ AS DATE); – Generates ‘2022-01-01’ for the previous year</p>
<p>Declare <span class="citation" data-cites="EffYearLike">@EffYearLike</span> varchar(8) = Cast(<span class="citation" data-cites="Year">@Year</span> as varchar) + ‘%’; – Generates ‘2023%’ for the previous year Declare <span class="citation" data-cites="EffYearLikePrevious">@EffYearLikePrevious</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev">@YearPrev</span> as varchar) + ‘%’; – Generates ‘2023%’ for the previous year Declare <span class="citation" data-cites="EffYearLikePrevious2">@EffYearLikePrevious2</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev2">@YearPrev2</span> as varchar) + ‘%’; – Generates ‘2023%’ for the previous year Declare <span class="citation" data-cites="EffYearLikePrevious3">@EffYearLikePrevious3</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev3">@YearPrev3</span> as varchar) + ‘%’; – Generates ‘2023%’ for the previous year Declare <span class="citation" data-cites="EffYearLikePrevious4">@EffYearLikePrevious4</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev4">@YearPrev4</span> as varchar) + ‘%’; – Generates ‘2023%’ for the previous year Declare <span class="citation" data-cites="EffYearLikePrevious5">@EffYearLikePrevious5</span> varchar(8) = Cast(<span class="citation" data-cites="YearPrev5">@YearPrev5</span> as varchar) + ‘%’; – Generates ‘2023%’ for the previous year</p>
<p>Declare <span class="citation" data-cites="ValueTypehoex">@ValueTypehoex</span> INT = 305; – 305 HOEX_Exemption Homeowner Exemption Declare <span class="citation" data-cites="ValueTypeimp">@ValueTypeimp</span> INT = 103; – 103 Imp Assessed Improvement Assessed Declare <span class="citation" data-cites="ValueTypeland">@ValueTypeland</span> INT = 102; – 102 Land Assessed Land Assessed Declare <span class="citation" data-cites="ValueTypetotal">@ValueTypetotal</span> INT = 109; – 109 Total Value Total Value Declare <span class="citation" data-cites="NetTaxableValueImpOnly">@NetTaxableValueImpOnly</span> INT = 458; – 458 Net Imp Only Net Taxable Value Imp Only Declare <span class="citation" data-cites="NetTaxableValueTotal">@NetTaxableValueTotal</span> INT = 455; – 455 Net Tax Value Net Taxable Value Declare <span class="citation" data-cites="NewConstruction">@NewConstruction</span> INT = 651; – 651 NewConstByCat New Construction Declare <span class="citation" data-cites="AssessedByCat">@AssessedByCat</span> INT = 470; –470 AssessedByCat Assessed Value</p>
<pre><code>
```{sql eval=FALSE, include=TRUE}


--Declare @Year int = 2024; -- Input THIS year here
DECLARE @TaxYear INT;
SET @TaxYear = YEAR(GETDATE());

Declare @YearPrev int = @Year - 1; -- Input the year here
Declare @YearPrevPrev int = @Year - 2; -- Input the year here

--VARCHAR String with the two letters plus last two of year, allows for NC Memos in this case
Declare @NCYear varchar(4) = 'NC' + Right(Cast(@Year as varchar), 2); -- This will create 'NC24'
Declare @NCYearPrevious varchar(4) = 'NC' + Right(Cast(@YearPrev as varchar), 2); -- This will create 'NC23'


--EXACT NO-DASHES '20230101'
Declare @EffYear0101Current varchar(8) = Cast(@Year as varchar) + '0101'; -- Generates '20230101' for the previous year
Declare @EffYear0101Previous varchar(8) = Cast(@YearPrev as varchar) + '0101'; -- Generates '20230101' for the previous year
Declare @EffYear0101PreviousPrevious varchar(8) = Cast(@YearPrevPrev as varchar) + '0101'; -- Generates '20230101' for the previous year

--EXACT DASHES '2023-01-01'
Declare @ValEffDateCurrent date = CAST(CAST(@Year as varchar) + '-01-01' AS DATE); -- Generates '2023-01-01' for the current year
Declare @ValEffDatePrevious date = CAST(CAST(@YearPrev as varchar) + '-01-01' AS DATE); -- Generates '2022-01-01' for the previous year
--And CAST(i.ValEffDate AS DATE) = '2023-01-01'

--LIKE Year with Perce Symbol 2023%
Declare @EffYear0101PreviousLike varchar(8) = Cast(@YearPrev as varchar) + '%'; -- Generates '20230101' for the previous year
--Where eff_year LIKE '2023%'Results include --20230101 --20230804
Declare @EffYear0101PreviousPreviousLike varchar(8) = Cast(@YearPrevPrev as varchar) + '%'; -- Generates '20230101' for the previous year
Declare @EffYear0101CurrentLike varchar(8) = Cast(@Year as varchar) + '%'; -- Generates '20230101' for the previous year


-- These ValueTypes are for the Cadastre Queries
Declare @ValueTypeimp INT = 103;
--    103 Imp Assessed Improvement Assessed
Declare @ValueTypeland INT = 102;
--    102 Land Assessed Land Assessed
Declare @ValueTypetotal INT = 109;
--    109 Total Value Total Value
Declare @NetTaxableValueImpOnly INT = 458;
--    458 Net Imp Only Net Taxable Value Imp Only
Declare @NetTaxableValueTotal INT = 455;
--    455 Net Tax Value Net Taxable Value

Declare @NewConstruction INT = 651;
--    651 NewConstByCat New Construction
Declare @AssessedByCat INT = 470;
--470 AssessedByCat Assessed Value


Declare @ValueTypehoex INT = 305;
--    305 HOEX_Exemption Homeowner Exemption
--NOTE: For HOEX from Cadaster, it will only pull fro a locked roll
  --If the current year roll is locked, and you use @Year no values will populate
  --If the @YearPrev is used, you will pull last year's cadasters not this years
</code></pre>
<p>```{sql eval=FALSE, include=TRUE}</p>
<p>–Divide by zero error fix.</p>
<p>,(wk.Worksheet_Total_Market / NULLIF(market.Tax_Year_Market, 0)) AS WorkMarket_Perc_CertMarket_Total</p>
<pre><code>





### Search Entire Database



```{sql eval=FALSE, include=TRUE}

--Find a table name like... 

SELECT * FROM information_schema.columns 
WHERE table_name LIKE 'CAD%'
OR table_name LIKE 'Value%'

SELECT * FROM information_schema.columns 
WHERE table_name LIKE 'TIF%';

--Find a table with a Column Name like...
SELECT * FROM information_schema.columns 
WHERE column_name LIKE 'TaxCalcDetail%';


SELECT * FROM information_schema.columns 
WHERE column_name LIKE '%Due%';







--Complex Example

SELECT
    tc.table_name AS foreign_table,
    kcu.column_name AS foreign_column,
    ccu.table_name AS primary_table,
    ccu.column_name AS primary_column
FROM
    information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu ON tc.constraint_name = kcu.constraint_name
    JOIN information_schema.constraint_column_usage AS ccu ON ccu.constraint_name = tc.constraint_name
WHERE
    tc.constraint_type = 'FOREIGN KEY'
    AND kcu.table_name = 'YourTableName'
    AND kcu.column_name = 'YourIDColumnName';
</code></pre>
<section id="row_number" class="level3">
<h3 class="anchored" data-anchor-id="row_number">ROW_NUMBER</h3>
<p>```{sql eval=FALSE, include=TRUE}</p>
<p>ROW_NUMBER() OVER (PARTITION BY ### ORDER BY ### DESC) AS RowNum</p>
</section>
</section>
</section>
<section id="explained" class="level1">
<h1>Explained:</h1>
<p>ROW_NUMBER() OVER (PARTITION BY #GroupByColumn# ORDER BY #FilterOutColumn# DESC) AS RowNum</p>
</section>
<section id="example" class="level1">
<h1>Example:</h1>
<p>ROW_NUMBER() OVER (PARTITION BY pm.lrsn ORDER BY v.Last_Updated DESC) AS RowNum</p>
<pre><code>


### TRIM()



```{sql eval=FALSE, include=TRUE}

# Newer Style, Post 2017
TRIM() &lt;- For SQL Server after 2017


# Older Style Pre 2017
LTRIM(RTRIM()) &lt;- For SQL Server before 2017 
</code></pre>
<section id="ctes" class="level3">
<h3 class="anchored" data-anchor-id="ctes">CTEs</h3>
<p>```{sql eval=FALSE, include=TRUE} WITH CTE_NameYouAssign AS ( Example: WITH CTE_1 AS (), CTE_2 AS (), CTE_3 AS ()</p>
<p>SELECT DISTINCT * FROM CTE_1 AS 1 LEFT JOIN CTE_2 AS 2 ON 1.lrsn=2.RevObjId LEFT JOIN CTE_3 AS 3 ON 1.lrsn=3.RevObjId</p>
<p>WHERE…</p>
<pre><code>


### CTEs with Variables Example 1



```{sql eval=FALSE, include=TRUE}
DECLARE @TaxYear INT = 2024; 
-- Current Tax Year -- Change this to the current tax year
DECLARE @MemoID VARCHAR(4); -- Specify an appropriate length

--WHERE m.memo_id='RY24'
SET @MemoID = CAST('RY' + RIGHT(CAST(@TaxYear AS VARCHAR(4)), 2) AS VARCHAR(4));


CTE_Memos_RY AS (
Select
m.lrsn
,m.memo_id
,m.memo_text AS RY_Memo

FROM memos AS m
WHERE m.memo_id = @MemoID
--WHERE m.memo_id='RY24'
AND m.status = 'A'
AND m.memo_line_number &lt;&gt; '1'
)
</code></pre>
</section>
<section id="ctes-with-variables-example-2" class="level3">
<h3 class="anchored" data-anchor-id="ctes-with-variables-example-2">CTEs with Variables Example 2</h3>
<p>```{sql eval=FALSE, include=TRUE} – !preview conn=conn</p>
<p>/<em> AsTxDBProd GRM_Main </em>/</p>
<p>DECLARE <span class="citation" data-cites="TaxYear">@TaxYear</span> INT = 2024; – Current Tax Year – Change this to the current tax year DECLARE <span class="citation" data-cites="MemoID">@MemoID</span> VARCHAR(4); – Specify an appropriate length</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>– By changing these years, you will have effectively changed all effective years</td>
</tr>
</tbody>
</table>
<p>–WHERE m.memo_id=‘RY24’ SET <span class="citation" data-cites="MemoID">@MemoID</span> = CAST(‘RY’ + RIGHT(CAST(<span class="citation" data-cites="TaxYear">@TaxYear</span> AS VARCHAR(4)), 2) AS VARCHAR(4));</p>
<p>DECLARE <span class="citation" data-cites="PrevTaxYear">@PrevTaxYear</span> INT = <span class="citation" data-cites="TaxYear">@TaxYear</span> - 1; – Now, derive other variables from <span class="citation" data-cites="TaxYear">@TaxYear</span> DECLARE <span class="citation" data-cites="PrimaryTransferDateFROM">@PrimaryTransferDateFROM</span> DATE = CAST(CAST(<span class="citation" data-cites="TaxYear">@TaxYear</span> AS VARCHAR) + ‘-01-01’ AS DATE); DECLARE <span class="citation" data-cites="PrimaryTransferDateTO">@PrimaryTransferDateTO</span> DATE = CAST(CAST(<span class="citation" data-cites="TaxYear">@TaxYear</span> AS VARCHAR) + ‘-12-31’ AS DATE);</p>
<p>DECLARE <span class="citation" data-cites="CertValueDateFROM">@CertValueDateFROM</span> INT = CAST(CAST(<span class="citation" data-cites="TaxYear">@TaxYear</span> AS VARCHAR) + ‘0101’ AS INT); DECLARE <span class="citation" data-cites="CertValueDateTO">@CertValueDateTO</span> INT = CAST(CAST(<span class="citation" data-cites="TaxYear">@TaxYear</span> AS VARCHAR) + ‘1231’ AS INT);</p>
<p>DECLARE <span class="citation" data-cites="PrevCertValueDateFROM">@PrevCertValueDateFROM</span> INT = CAST(CAST(<span class="citation" data-cites="PrevTaxYear">@PrevTaxYear</span> AS VARCHAR) + ‘0101’ AS INT); DECLARE <span class="citation" data-cites="PrevCertValueDateTO">@PrevCertValueDateTO</span> INT = CAST(CAST(<span class="citation" data-cites="PrevTaxYear">@PrevTaxYear</span> AS VARCHAR) + ‘1231’ AS INT);</p>
<p>– Assuming you want to construct <span class="citation" data-cites="LandModelId">@LandModelId</span> based on the year too, here’s a potential way to do it: – Example assumes the prefix ‘70’ is constant and the year is appended to it. DECLARE <span class="citation" data-cites="LandModelIdPrefix">@LandModelIdPrefix</span> VARCHAR(2) = ‘70’; – This is just an example. Adjust as needed. DECLARE <span class="citation" data-cites="LandModelId">@LandModelId</span> INT = CAST(<span class="citation" data-cites="LandModelIdPrefix">@LandModelIdPrefix</span> + CAST(<span class="citation" data-cites="TaxYear">@TaxYear</span> AS VARCHAR) AS INT);</p>
<p>/*</p>
<p>EXAMPLES without CAST: –DECLARE <span class="citation" data-cites="LandModelIDYear">@LandModelIDYear</span> INT = 2023; – Current Land Model ID Year – Change this to the desired year Declare <span class="citation" data-cites="PrimaryTransferDateFROM">@PrimaryTransferDateFROM</span> DATE = ‘2023-01-01’; Declare <span class="citation" data-cites="PrimaryTransferDateTO">@PrimaryTransferDateTO</span> DATE = ‘2023-12-31’; –pxfer_date –AND tr.pxfer_date BETWEEN ‘2023-01-01’ AND ‘2023-12-31’</p>
<p>Declare <span class="citation" data-cites="CertValueDateFROM">@CertValueDateFROM</span> INT = ‘20230101’; Declare <span class="citation" data-cites="CertValueDateTO">@CertValueDateTO</span> INT = ‘20231231’; –v.eff_year —WHERE v.eff_year BETWEEN 20230101 AND 20231231</p>
<p>–DECLARE <span class="citation" data-cites="VariableName">@VariableName</span> INT = ’’;</p>
<p>–Change year 2023, 2024, 2025, etc. ‘702023’ DECLARE <span class="citation" data-cites="LandModelId">@LandModelId</span> INT = ‘702024’; */</p>
<p>WITH</p>
</section>
<section id="cte_parcelmaster-as" class="level2">
<h2 class="anchored" data-anchor-id="cte_parcelmaster-as">CTE_ParcelMaster AS (</h2>
</section>
<section id="parcelmaster" class="level2">
<h2 class="anchored" data-anchor-id="parcelmaster">–ParcelMaster</h2>
<p>Select Distinct CASE WHEN pm.neighborhood &gt;= 9000 THEN ‘Manufactured_Homes’ WHEN pm.neighborhood &gt;= 6003 THEN ‘District_6’ WHEN pm.neighborhood = 6002 THEN ‘Manufactured_Homes’ WHEN pm.neighborhood = 6001 THEN ‘District_6’ WHEN pm.neighborhood = 6000 THEN ‘Manufactured_Homes’ WHEN pm.neighborhood &gt;= 5003 THEN ‘District_5’ WHEN pm.neighborhood = 5002 THEN ‘Manufactured_Homes’ WHEN pm.neighborhood = 5001 THEN ‘District_5’ WHEN pm.neighborhood = 5000 THEN ‘Manufactured_Homes’ WHEN pm.neighborhood &gt;= 4000 THEN ‘District_4’ WHEN pm.neighborhood &gt;= 3000 THEN ‘District_3’ WHEN pm.neighborhood &gt;= 2000 THEN ‘District_2’ WHEN pm.neighborhood &gt;= 1021 THEN ‘District_1’ WHEN pm.neighborhood = 1020 THEN ‘Manufactured_Homes’ WHEN pm.neighborhood &gt;= 1001 THEN ‘District_1’ WHEN pm.neighborhood = 1000 THEN ‘Manufactured_Homes’ WHEN pm.neighborhood &gt;= 451 THEN ‘Commercial’ WHEN pm.neighborhood = 450 THEN ‘Specialized_Cell_Towers’ WHEN pm.neighborhood &gt;= 1 THEN ‘Commercial’ WHEN pm.neighborhood = 0 THEN ‘N/A_or_Error’ ELSE NULL END AS District</p>
<p>– # District SubClass ,pm.neighborhood AS GEO ,TRIM(pm.NeighborHoodName) AS GEO_Name ,pm.lrsn ,TRIM(pm.pin) AS PIN ,TRIM(pm.AIN) AS AIN ,pm.ClassCD ,TRIM(pm.PropClassDescr) AS Property_Class_Description ,TRIM(pm.TAG) AS TAG ,TRIM(pm.DisplayName) AS Owner ,TRIM(pm.DisplayDescr) AS LegalDescription ,TRIM(pm.SitusAddress) AS SitusAddress ,TRIM(pm.SitusCity) AS SitusCity ,TRIM(pm.SitusState) AS SitusState ,TRIM(pm.SitusZip) AS SitusZip ,TRIM(pm.AttentionLine) AS AttentionLine ,TRIM(pm.MailingAddress) AS MailingAddress ,TRIM(pm.AddlAddrLine) AS AddlAddrLine ,TRIM(pm.MailingCityStZip) AS MailingCityStZip ,TRIM(pm.MailingCity) AS MailingCity ,TRIM(pm.MailingState) AS MailingState ,TRIM(pm.MailingZip) AS MailingZip</p>
<p>,pm.LegalAcres –,pm.WorkValue_Land –,pm.WorkValue_Impv –,pm.WorkValue_Total –,pm.CostingMethod ,pm.Improvement_Status – &lt;Improved vs Vacant</p>
<p>From TSBv_PARCELMASTER AS pm</p>
<p>Where pm.EffStatus = ‘A’ AND pm.ClassCD NOT LIKE ‘070%’ AND pm.neighborhood &lt;&gt; 0 AND pm.neighborhood IS NOT NULL ),</p>
<p>CTE_LandInfluenceCodesKey AS ( SELECT tbl_element AS InfluenceCode, tbl_element_desc AS InfluenceCodeDescription FROM codes_table WHERE TRIM(tbl_type_code) LIKE ‘landinf%’ AND code_status=‘A’ ),</p>
<p>CTE_LegendKey AS ( SELECT TRIM(sr.tbl_element) AS Site_Rating, TRIM(sr.tbl_element_desc) AS Legend, CASE WHEN TRIM(sr.tbl_element_desc) LIKE ‘Leg%’ THEN CAST(RIGHT(TRIM(sr.tbl_element_desc),2) AS INT) ELSE CASE WHEN sr.tbl_element_desc IS NULL THEN CAST(1 AS INT) WHEN sr.tbl_element_desc LIKE ‘No%’ THEN CAST(1 AS INT) WHEN sr.tbl_element_desc LIKE ‘Average%’ THEN CAST(2 AS INT) WHEN sr.tbl_element_desc LIKE ‘Good%’ THEN CAST(3 AS INT) WHEN sr.tbl_element_desc LIKE ‘Excellent%’ THEN CAST(4 AS INT) ELSE 0 END END AS LegendNum</p>
<p>FROM codes_table AS sr</p>
<p>WHERE sr.tbl_type_code=‘siterating’ AND code_status = ‘A’</p>
<p>–JOIN ON –ON ld.SiteRating = sr.tbl_element ),</p>
<p>CTE_LandDetails AS ( SELECT lh.RevObjId AS lrsn , ld.LandType , CONCAT_WS(‘-’,ld.LandType,lt.land_type_desc) AS LandType_Desc , STRING_AGG (ld.LDAcres, ‘,’) AS LDAcres , STRING_AGG (leg.Legend, ‘,’) AS Legend</p>
<p>–Land Header FROM LandHeader AS lh –Land Detail JOIN LandDetail AS ld ON lh.id=ld.LandHeaderId AND ld.EffStatus=‘A’ AND ld.PostingSource=‘A’ AND lh.PostingSource=ld.PostingSource –Legend Key<br>
LEFT JOIN CTE_LegendKey AS leg ON ld.SiteRating = leg.Site_Rating –Land Types LEFT JOIN land_types AS lt ON ld.LandType=lt.land_type –Land Influence LEFT JOIN LandInfluence AS li ON li.ObjectId = ld.Id AND li.EffStatus=‘A’ AND li.PostingSource=‘A’ –Land Influcnce Code Key for Description LEFT JOIN CTE_LandInfluenceCodesKey AS lic ON lic.InfluenceCode=li.InfluenceCode</p>
<p>WHERE lh.EffStatus= ‘A’ AND lh.PostingSource=‘A’</p>
<p>GROUP BY lh.RevObjId</p>
<p>– ld.LDAcres , ld.LandType , lt.land_type_desc – leg.Legend</p>
<p>),</p>
<p>CTE_WorksheetMarketValues AS( SELECT r.lrsn, r.method AS PriceMethod, r.land_mkt_val_inc AS Worksheet_Land, (r.income_value - r.land_mkt_val_cost) AS Worksheet_Imp, r.income_value AS Worksheet_Total</p>
<p>FROM reconciliation AS r –ON parcel.lrsn = r.lrsn WHERE r.status = ‘W’ AND r.method = ‘I’ –AND r.land_model = <span class="citation" data-cites="LandModelId">@LandModelId</span></p>
<p>UNION ALL</p>
<p>SELECT r.lrsn, r.method AS PriceMethod, r.land_mkt_val_cost AS Worksheet_Land, r.cost_value AS Worksheet_Imp, (r.cost_value + r.land_mkt_val_cost) AS Worksheet_Total</p>
<p>FROM reconciliation AS r –ON parcel.lrsn = r.lrsn WHERE r.status=‘W’ AND r.method = ‘C’ –AND r.land_model = <span class="citation" data-cites="LandModelId">@LandModelId</span></p>
<p>–ORDER BY GEO, PIN; ),</p>
<p>CTE_ParcelCounter AS ( SELECT Owner ,COUNT(lrsn) AS CountParcels_PerOwner</p>
<p>FROM CTE_ParcelMaster WHERE GEO = ‘42’ GROUP BY Owner ),</p>
<p>CTE_LegalAcresCounter AS ( SELECT Owner ,COUNT(LegalAcres) AS CountLegalAcres_PerOwner</p>
<p>FROM CTE_ParcelMaster WHERE GEO = ‘42’ GROUP BY Owner ),</p>
<table class="caption-top table">
<colgroup>
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">–CTE_TransferSales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CTE_TransferSales AS ( SELECT DISTINCT – pmd.[GEO_Name], t.lrsn, t.status, –Transfer Table Sale Details t.AdjustedSalePrice AS SalePrice, CAST(t.pxfer_date AS DATE) AS SaleDate, TRIM(t.SaleDesc) AS SaleDescr, TRIM(t.TfrType) AS TranxType, TRIM(t.DocNum) AS DocNumber – Multiples will have the same DocNum FROM transfer AS t – ON t.lrsn for joins WHERE t.status = ‘A’ AND t.AdjustedSalePrice &lt;&gt; ‘0’ AND t.pxfer_date BETWEEN <span class="citation" data-cites="PrimaryTransferDateFROM">@PrimaryTransferDateFROM</span> AND <span class="citation" data-cites="PrimaryTransferDateTO">@PrimaryTransferDateTO</span> –AND t.pxfer_date BETWEEN ‘2023-01-01’ AND ‘2023-12-31’ ),</td>
</tr>
<tr class="even">
<td style="text-align: left;">CTE_Cert AS ( SELECT lrsn, –Certified Values v.land_market_val AS CertValue_Land_Current, v.imp_val AS CertValue_Imp_Current, (v.imp_val + v.land_market_val) AS CertValue_Total_Current, v.eff_year AS Tax_Year_Cert, ROW_NUMBER() OVER (PARTITION BY v.lrsn ORDER BY v.last_update DESC) AS RowNumber FROM valuation AS v WHERE v.eff_year BETWEEN <span class="citation" data-cites="CertValueDateFROM">@CertValueDateFROM</span> AND <span class="citation" data-cites="CertValueDateTO">@CertValueDateTO</span> –Change to desired year AND v.status = ‘A’ ),</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CTE_Cert_Prev AS ( SELECT lrsn, –Certified Values v.land_market_val AS CertValue_Land_Previous, v.imp_val AS CertValue_Imp_Previous, (v.imp_val + v.land_market_val) AS CertValue_Total_Previous, v.eff_year AS Tax_Year_Cert, ROW_NUMBER() OVER (PARTITION BY v.lrsn ORDER BY v.last_update DESC) AS RowNumber FROM valuation AS v –WHERE v.eff_year BETWEEN <span class="citation" data-cites="PrevCertValueDateFROM">@PrevCertValueDateFROM</span> AND <span class="citation" data-cites="PrevCertValueDateTO">@PrevCertValueDateTO</span> WHERE v.eff_year BETWEEN ‘20230101’ AND ‘20231231’ –Change to desired year AND v.status = ‘A’ ),</td>
</tr>
<tr class="even">
<td style="text-align: left;">CTE_Assessed AS ( SELECT lrsn, –Assessed Values v.land_assess AS AssessedValue_Land_wEx, v.imp_assess AS AssessedValue_Imp, (v.imp_assess + v.land_assess) AS AssessedValue_Total, v.eff_year AS Tax_Year_Assessed, ROW_NUMBER() OVER (PARTITION BY v.lrsn ORDER BY v.last_update DESC) AS RowNumber FROM valuation AS v WHERE v.eff_year BETWEEN <span class="citation" data-cites="CertValueDateFROM">@CertValueDateFROM</span> AND <span class="citation" data-cites="CertValueDateTO">@CertValueDateTO</span> –Change to desired year AND v.status = ‘A’ ),</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CTE_Memos_RY AS ( Select m.lrsn ,m.memo_id ,m.memo_text AS RY_Memo</td>
</tr>
<tr class="even">
<td style="text-align: left;">FROM memos AS m WHERE m.memo_id = <span class="citation" data-cites="MemoID">@MemoID</span> –WHERE m.memo_id=‘RY24’ AND m.status = ‘A’ AND m.memo_line_number &lt;&gt; ‘1’ )</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SELECT DISTINCT *</td>
</tr>
</tbody>
</table>
<p>FROM CTE_ParcelMaster AS pmd Left Join CTE_WorksheetMarketValues AS ws On ws.lrsn = pmd.lrsn Left Join CTE_ParcelCounter AS pc On pmd.owner = pc.owner –,COUNT(lrsn) AS CountParcels_PerOwner Left Join CTE_LegalAcresCounter AS lac On pmd.owner = lac.owner –,COUNT(LegalAcres) AS CountLegalAcres_PerOwner Left Join CTE_Cert AS cv ON pmd.lrsn=cv.lrsn AND cv.RowNumber = ‘1’ Left Join CTE_Cert_Prev AS cvp ON pmd.lrsn=cvp.lrsn AND cvp.RowNumber = ‘1’ Left Join CTE_Memos_RY AS mry On pmd.lrsn = mry.lrsn</p>
<p>Where pmd.GEO = ‘42’</p>
<p>Order By pmd.Owner;</p>
<pre><code>


### CASE_Single vs Multiple



```{sql eval=FALSE, include=TRUE}

# Case Single
CASE
  WHEN field1 = 'value1' THEN 'Category1'
  ELSE 'Other'
END AS [YourNewColumnName]

# Case Multiple

CASE
  WHEN field1 = 'value1' THEN 'Category1'
  WHEN field1 = 'value2' THEN 'Category2'
  WHEN field1 = 'value3' THEN 'Category3'
  ELSE 'Other'
END AS [YourNewColumnName]

</code></pre>
<section id="insert-into-text" class="level3">
<h3 class="anchored" data-anchor-id="insert-into-text">Insert into text:</h3>
<p>```{sql eval=FALSE, include=TRUE} SUBSTRING(column, 1, 3) + ‘-’ + SUBSTRING(column, 4, 3) AS TAG,</p>
<p>Example: SELECT DISTINCT TAGDescr, SUBSTRING(TAGDescr, 1, 3) + ‘-’ + SUBSTRING(TAGDescr, 4, 3) AS TAG, LevyRate</p>
<p>FROM KCv_TAGLevyRate22a ORDER BY TAGDescr</p>
<pre><code>


------------------------------------------------------------------------

## CAST Examples



```{sql eval=FALSE, include=TRUE}

CAST(expression AS data_type)
SELECT CAST(42 AS VARCHAR(10));
CONVERT(data_type, expression [, style])

Data Type Options:
SELECT CAST(ColumnName AS VARCHAR(10)) AS NumericToString;
SELECT CAST(ColumnName AS FLOAT) AS StringToNumeric;
SELECT CAST(ColumnName AS DATE) AS StringToDate;
SELECT CAST(GETDATE() AS VARCHAR(25)) AS DateToString;
SELECT CAST(ColumnName AS DECIMAL(10, 2)) AS IntegerToDecimal;
SELECT CAST(ColumnName AS INT) AS DecimalToInteger;

SELECT
    CASE WHEN CAST('True' AS BIT) = 1 THEN 'Yes'
         ELSE 'No' END AS StringToBoolean;
         
SELECT IIF(CAST('False' AS BIT) = 1, 'Yes', 'No') AS StringToBoolean;

</code></pre>
<hr>
</section>
</section>
<section id="common-syntax-references" class="level2">
<h2 class="anchored" data-anchor-id="common-syntax-references">Common Syntax References</h2>
<p>ASC Sorts the result set in ascending order CAST Converts a value (of any type) into a specified datatype DESC Sorts the result set in descending order DISTINCT Selects only distinct (different) values BETWEEN Selects values within a given range CASE Creates different outputs based on conditions LIKE Searches for a specified pattern in a column LIMIT Specifies the number of records to return in the result set NOT Only includes rows where a condition is not true NOT NULL A constraint that enforces a column to not accept NULL values UNION Combines the result set of two or more SELECT statements (only distinct values) UNION ALL Combines the result set of two or more SELECT statements (allows duplicate values)</p>
<hr>
</section>
<section id="cast-explained" class="level2">
<h2 class="anchored" data-anchor-id="cast-explained">CAST Explained</h2>
<p>In SQL Server, the <code>CAST</code> function is used to explicitly convert one data type to another. The basic syntax for the <code>CAST</code> function is as follows:</p>
<p><code>{sql eval=FALSE, include=TRUE} CAST(expression AS data_type)</code></p>
<p>Here: - <code>expression</code>: The value or column that you want to convert to another data type. - <code>data_type</code>: The target data type to which you want to convert the expression.</p>
<p>For example, to convert a numeric value to a varchar data type, you can use:</p>
<p><code>{sql eval=FALSE, include=TRUE} SELECT CAST(42 AS VARCHAR(10));</code></p>
<p>This will convert the numeric value 42 to a varchar data type, resulting in the string <code>'42'</code>.</p>
<p>Note that when using <code>CAST</code>, be careful about potential data loss or conversion errors, especially when converting between different data types that have different ranges or precision.</p>
<p>Additionally, SQL Server also provides the <code>CONVERT</code> function, which is similar to <code>CAST</code> but provides more formatting options for certain data types, like converting dates to specific formats. The syntax for <code>CONVERT</code> is:</p>
<p><code>{sql eval=FALSE, include=TRUE} CONVERT(data_type, expression [, style])</code></p>
<p>Where <code>style</code> is an optional parameter used for formatting when converting dates. If you don’t need specific formatting, you can use <code>CAST</code> as it is more concise.</p>
<p>Let’s demonstrate various <code>CAST</code> data type options in SQL Server using some examples:</p>
<ol type="1">
<li>Numeric to String Conversion:</li>
</ol>
<p><code>{sql eval=FALSE, include=TRUE} SELECT CAST(42 AS VARCHAR(10)) AS NumericToString;</code></p>
<p>Output:</p>
<pre><code>NumericToString
--------------
42</code></pre>
<ol start="2" type="1">
<li>String to Numeric Conversion:</li>
</ol>
<p><code>{sql eval=FALSE, include=TRUE} SELECT CAST('3.14' AS FLOAT) AS StringToNumeric;</code></p>
<p>Output:</p>
<pre><code>StringToNumeric
---------------
3.14</code></pre>
<ol start="3" type="1">
<li>String to Date Conversion:</li>
</ol>
<p><code>{sql eval=FALSE, include=TRUE} CAST('2023-08-03' AS DATE) AS StringToDate;</code></p>
<p>Output:</p>
<pre><code>StringToDate
------------
2023-08-03</code></pre>
<ol start="4" type="1">
<li>Date to String Conversion:</li>
</ol>
<p><code>{sql eval=FALSE, include=TRUE} CAST(GETDATE() AS VARCHAR(25)) AS DateToString;</code></p>
<p>Output (will vary based on the current date):</p>
<pre><code>DateToString
-------------------------
2023-08-03 15:30:00.123</code></pre>
<ol start="5" type="1">
<li>Integer to Decimal Conversion:</li>
</ol>
<p><code>{sql eval=FALSE, include=TRUE} CAST(123 AS DECIMAL(10, 2)) AS IntegerToDecimal;</code></p>
<p>Output:</p>
<pre><code>IntegerToDecimal
----------------
123.00</code></pre>
<ol start="6" type="1">
<li>Decimal to Integer Conversion (Note: Truncation will occur):</li>
</ol>
<p><code>{sql eval=FALSE, include=TRUE} CAST(456.78 AS INT) AS DecimalToInteger;</code></p>
<p>Output:</p>
<pre><code>DecimalToInteger
----------------
456</code></pre>
<ol start="7" type="1">
<li>String to Boolean Conversion (Using CASE expression):</li>
</ol>
<p>```{sql eval=FALSE, include=TRUE} SELECT CASE WHEN CAST(‘True’ AS BIT) = 1 THEN ‘Yes’ ELSE ‘No’ END AS StringToBoolean; FROM table_name</p>
<pre><code>


Output:
</code></pre>
</section>
<section id="stringtoboolean" class="level2">
<h2 class="anchored" data-anchor-id="stringtoboolean">StringToBoolean</h2>
<p>Yes</p>
<pre><code>
8.  String to Boolean Conversion (Using IIF function):



```{sql eval=FALSE, include=TRUE}
SELECT 

  IIF(CAST('False' AS BIT) = 1, 'Yes', 'No') AS StringToBoolean

FROM </code></pre>
<p>Output:</p>
<pre><code>StringToBoolean
--------------
No</code></pre>
<p>Remember that the exact output and behavior will depend on the specific values and data types used in your database. Always be cautious when performing data type conversions, as unexpected results may occur if the data cannot be converted correctly.</p>
<hr>
</section>
<section id="gpt-4-explains-trim-vs-trim" class="level2">
<h2 class="anchored" data-anchor-id="gpt-4-explains-trim-vs-trim">GPT-4 Explains TRIM vs TRIM</h2>
<p>```{sql eval=FALSE, include=TRUE}</p>
<p>LTRIM(RTRIM())</p>
<p>#vs</p>
<p>TRIM()</p>
<pre><code>


The difference between `LTRIM(RTRIM(pm.pin)) AS [PIN]` and
`TRIM(pm.pin) AS [PIN]` in SQL Server comes down to the versions of SQL
Server you are using.

Before SQL Server 2017, the `TRIM` function did not exist. So, to remove
both leading and trailing spaces, you had to use
`LTRIM(RTRIM(pm.pin)) AS [PIN]`. This first applies the `RTRIM` function
to remove trailing spaces and then the `LTRIM` function to remove
leading spaces.

Starting from SQL Server 2017, Microsoft introduced the `TRIM` function,
which removes both leading and trailing spaces from a string. So, in SQL
Server 2017 and later versions, you can simply use
`TRIM(pm.pin) AS [PIN]` to achieve the same result as
`LTRIM(RTRIM(pm.pin)) AS [PIN]`.

In terms of functionality, there's no practical difference between the
two in SQL Server 2017 and later -- they both remove leading and
trailing spaces. However, `TRIM` is more concise and easier to read. So
if you're using a newer version of SQL Server, I'd recommend using
`TRIM` for simplicity.

Do keep in mind that if your scripts need to be backward compatible with
versions of SQL Server prior to 2017, you should stick with using
`LTRIM(RTRIM())`.

------------------------------------------------------------------------

## TABLE QUERIES - BASICS OF THE CODE YOU NEED TO GRAB INFORMATION FROM A SQL DATABASE, MOST MATERIALS FROM W3 SCHOOLS

[W3 Schools
LINK](https://www.w3schools.com/sql/sql_quickref.asp "W3 Schools LINK")

------------------------------------------------------------------------



```{sql eval=FALSE, include=TRUE}


--**-- SELECT TYPES

--SELECT
    SELECT column_name(s)
FROM table_name

--SELECT *  
    SELECT *
FROM table_name

--SELECT DISTINCT   
    SELECT DISTINCT column_name(s)
FROM table_name

--SELECT INTO   
    SELECT *
INTO new_table_name [IN externaldatabase]
FROM old_table_name
or

SELECT column_name(s)
INTO new_table_name [IN externaldatabase]
FROM old_table_name

--SELECT TOP    
    SELECT TOP number|percent column_name(s)
FROM table_name

--**--JOIN TYPES

--INNER JOIN    
    SELECT column_name(s)
FROM table_name1
INNER JOIN table_name2
ON table_name1.column_name=table_name2.column_name

--LEFT JOIN 
    SELECT column_name(s)
FROM table_name1
LEFT JOIN table_name2
ON table_name1.column_name=table_name2.column_name

--RIGHT JOIN    
    SELECT column_name(s)
FROM table_name1
RIGHT JOIN table_name2
ON table_name1.column_name=table_name2.column_name

--FULL JOIN 
    SELECT column_name(s)
FROM table_name1
FULL JOIN table_name2
ON table_name1.column_name=table_name2.column_name


--**-- CONDITIONS

--WHERE
    SELECT column_name(s)
FROM table_name
WHERE column_name operator value

--IN
    SELECT column_name(s)
FROM table_name
WHERE column_name
IN (value1,value2,..)

--AS (alias)    
SELECT column_name AS column_alias
FROM table_name
or

SELECT column_name
FROM table_name  AS table_alias

--AND / OR  
SELECT column_name(s)
FROM table_name
WHERE condition
AND|OR condition

--BETWEEN
    SELECT column_name(s)
FROM table_name
WHERE column_name
BETWEEN value1 AND value2

--LIKE
    SELECT column_name(s)
FROM table_name
WHERE column_name LIKE pattern

--**-- ORDERING RESULTS OF QUERY (FOR SELECT, DIFFERENT THAN GROUP BY)

--ORDER BY  
    SELECT column_name(s)
FROM table_name
ORDER BY column_name [ASC|DESC]


--**-- AGGREGATES 


--GROUP BY  
    SELECT column_name, aggregate_function(column_name)
FROM table_name
WHERE column_name operator value
GROUP BY column_name

--HAVING
    SELECT column_name, aggregate_function(column_name)
FROM table_name
WHERE column_name operator value
GROUP BY column_name
HAVING aggregate_function(column_name) operator value
</code></pre>
</section>
<section id="sub-queries" class="level2">
<h2 class="anchored" data-anchor-id="sub-queries">SUB QUERIES</h2>
<section id="exists" class="level3">
<h3 class="anchored" data-anchor-id="exists">EXISTS</h3>
<p>The SQL EXISTS Operator is used to test for the existence of any record in a subquery. The EXISTS operator returns TRUE if the subquery returns one or more records.</p>
<p>```{sql eval=FALSE, include=TRUE} IF EXISTS (SELECT * FROM table_name WHERE id = ?) BEGIN</p>
<pre><code>


IF EXISTS (SELECT \* FROM table_name WHERE id = ?) BEGIN --do what needs
to be done if exists END ELSE BEGIN --do what needs to be done if not
END

CTE ((WITH common_table_expression)) (Transact-SQL)
&lt;https://learn.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver16&gt;



```{sql eval=FALSE, include=TRUE}</code></pre>
<p>WITH CTE_NameYouAssign AS ( SELECT column1 column2 column3 ROW_NUMBER() OVER (PARTITION BY column3 ORDER BY column1 DESC) AS RowNum FROM TableNameYouAreReferencing AS aliashere WHERE columnwhatever = ‘some condition’ )</p>
<p>SELECT DISTINCT a.column1 a.column2 a.column3 a.column4 a.column5 b.column – from CTE above, uses table join alias below, this is the part that confused me.</p>
<p>FROM primarytable AS a LEFT OUTER JOIN CTE_NameYouAssign AS b ON a.columnkey=b.columnkey WHERE a.column1 = ‘some condition’ AND a.column2 = ‘some condition’ ORDER BY columnwhatever;</p>
<p>–**– COMBINING QUERIES</p>
<p>–**– APPEND TWO MATCHING TABLES (LIKE APPEND IN POWER QUERY)</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>–UNION SELECT column_name(s) FROM table_name1 UNION SELECT column_name(s) FROM table_name2</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>–UNION ALL SELECT column_name(s) FROM table_name1 UNION ALL SELECT column_name(s) FROM table_name2</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: left;">QUERY-ONLY ABOVE THIS LINE DATABASE ALTERING CODE BELOW THIS LINE, USE CAUTION, RUN IN TEST BEFORE COMMITTING CHANGES</td>
</tr>
<tr class="even">
<td style="text-align: left;">FOR PRACTICE OR PERSONAL USE SEE: SQL Server 2022 Express is a free edition of SQL Server, ideal for development and production for desktop, web, and small server applications. <a href="https://www.microsoft.com/en-us/sql-server/sql-server-downloads?rtc=1" class="uri">https://www.microsoft.com/en-us/sql-server/sql-server-downloads?rtc=1</a></td>
</tr>
</tbody>
</table>
<p>–** DATABASE &amp; TABLE MAINTENCE –**–DATABASE MAINTENCE –CREATE DATABASE<br>
CREATE DATABASE database_name</p>
<p>–DROP DATABASE DROP DATABASE database_name</p>
<p>–**–TABLE MAINTENCE</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>–CREATE TABLE<br>
CREATE TABLE table_name ( column_name1 data_type, column_name2 data_type, column_name3 data_type, … )</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>–CREATE INDEX</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<pre><code>CREATE INDEX index_name</code></pre>
<p>ON table_name (column_name) or</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>CREATE UNIQUE INDEX index_name ON table_name (column_name)</p>
<p>–INSERT INTO</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<pre><code>INSERT INTO table_name</code></pre>
<p>VALUES (value1, value2, value3,….) or</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>INSERT INTO table_name (column1, column2, column3,…) VALUES (value1, value2, value3,….)</p>
<p>–CREATE VIEW</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<pre><code>CREATE VIEW view_name AS</code></pre>
<p>SELECT column_name(s) FROM table_name WHERE condition</p>
<p>–DELETE</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<pre><code>DELETE FROM table_name</code></pre>
<p>WHERE some_column=some_value or</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>DELETE FROM table_name (Note: Deletes the entire table!!)</p>
<p>–DROP INDEX</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<pre><code>DROP INDEX table_name.index_name (SQL Server)</code></pre>
<p>DROP INDEX index_name ON table_name (MS Access) DROP INDEX index_name (DB2/Oracle) ALTER TABLE table_name DROP INDEX index_name (MySQL)</p>
<p>–DROP TABLE</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>DROP TABLE table_name</p>
<p>–ALTER TABLE</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>ALTER TABLE table_name ADD column_name datatype or</p>
<p>–ALTER TABLE table_name</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>DROP COLUMN column_name</p>
<p>–TRUNCATE TABLE</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>TRUNCATE TABLE table_name</p>
<p>–UPDATE</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<pre><code>UPDATE table_name</code></pre>
<p>SET column1=value, column2=value,… WHERE some_column=some_value</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">SQL Keywords Reference <a href="https://www.w3schools.com/sql/sql_ref_keywords.asp" class="uri">https://www.w3schools.com/sql/sql_ref_keywords.asp</a></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Keyword Description ADD Adds a column in an existing table ADD CONSTRAINT Adds a constraint after a table is already created ALL Returns true if all of the subquery values meet the condition ALTER Adds, deletes, or modifies columns in a table, or changes the data type of a column in a table ALTER COLUMN Changes the data type of a column in a table ALTER TABLE Adds, deletes, or modifies columns in a table AND Only includes rows where both conditions is true ANY Returns true if any of the subquery values meet the condition AS Renames a column or table with an alias ASC Sorts the result set in ascending order BACKUP DATABASE Creates a back up of an existing database BETWEEN Selects values within a given range CASE Creates different outputs based on conditions CHECK A constraint that limits the value that can be placed in a column COLUMN Changes the data type of a column or deletes a column in a table CONSTRAINT Adds or deletes a constraint CREATE Creates a database, index, view, table, or procedure CREATE DATABASE Creates a new SQL database CREATE INDEX Creates an index on a table (allows duplicate values) CREATE OR REPLACE VIEW Updates a view CREATE TABLE Creates a new table in the database CREATE PROCEDURE Creates a stored procedure CREATE UNIQUE INDEX Creates a unique index on a table (no duplicate values) CREATE VIEW Creates a view based on the result set of a SELECT statement DATABASE Creates or deletes an SQL database DEFAULT A constraint that provides a default value for a column DELETE Deletes rows from a table DESC Sorts the result set in descending order DISTINCT Selects only distinct (different) values DROP Deletes a column, constraint, database, index, table, or view DROP COLUMN Deletes a column in a table DROP CONSTRAINT Deletes a UNIQUE, PRIMARY KEY, FOREIGN KEY, or CHECK constraint DROP DATABASE Deletes an existing SQL database DROP DEFAULT Deletes a DEFAULT constraint DROP INDEX Deletes an index in a table DROP TABLE Deletes an existing table in the database DROP VIEW Deletes a view EXEC Executes a stored procedure EXISTS Tests for the existence of any record in a subquery FOREIGN KEY A constraint that is a key used to link two tables together FROM Specifies which table to select or delete data from FULL OUTER JOIN Returns all rows when there is a match in either left table or right table GROUP BY Groups the result set (used with aggregate functions: COUNT, MAX, MIN, SUM, AVG) HAVING Used instead of WHERE with aggregate functions IN Allows you to specify multiple values in a WHERE clause INDEX Creates or deletes an index in a table INNER JOIN Returns rows that have matching values in both tables INSERT INTO Inserts new rows in a table INSERT INTO SELECT Copies data from one table into another table IS NULL Tests for empty values IS NOT NULL Tests for non-empty values JOIN Joins tables LEFT JOIN Returns all rows from the left table, and the matching rows from the right table LIKE Searches for a specified pattern in a column LIMIT Specifies the number of records to return in the result set NOT Only includes rows where a condition is not true NOT NULL A constraint that enforces a column to not accept NULL values OR Includes rows where either condition is true ORDER BY Sorts the result set in ascending or descending order OUTER JOIN Returns all rows when there is a match in either left table or right table PRIMARY KEY A constraint that uniquely identifies each record in a database table PROCEDURE A stored procedure RIGHT JOIN Returns all rows from the right table, and the matching rows from the left table ROWNUM Specifies the number of records to return in the result set SELECT Selects data from a database SELECT DISTINCT Selects only distinct (different) values SELECT INTO Copies data from one table into a new table SELECT TOP Specifies the number of records to return in the result set SET Specifies which columns and values that should be updated in a table TABLE Creates a table, or adds, deletes, or modifies columns in a table, or deletes a table or data inside a table TOP Specifies the number of records to return in the result set TRUNCATE TABLE Deletes the data inside a table, but not the table itself UNION Combines the result set of two or more SELECT statements (only distinct values) UNION ALL Combines the result set of two or more SELECT statements (allows duplicate values) UNIQUE A constraint that ensures that all values in a column are unique UPDATE Updates existing rows in a table VALUES Specifies the values of an INSERT INTO statement VIEW Creates, updates, or deletes a view WHERE Filters a result set to include only records that fulfill a specified condition</td>
</tr>
</tbody>
</table>
<p>ADDITIONAL RESOURCES - SQL Server Functions <a href="https://www.w3schools.com/sql/sql_ref_sqlserver.asp" class="uri">https://www.w3schools.com/sql/sql_ref_sqlserver.asp</a> ——————————————————————————————————————————————————– –SQL Server String Functions Function Description ASCII Returns the ASCII value for the specific character CHAR Returns the character based on the ASCII code CHARINDEX Returns the position of a substring in a string CONCAT Adds two or more strings together Concat with + Adds two or more strings together CONCAT_WS Adds two or more strings together with a separator DATALENGTH Returns the number of bytes used to represent an expression DIFFERENCE Compares two SOUNDEX values, and returns an integer value FORMAT Formats a value with the specified format LEFT Extracts a number of characters from a string (starting from left) LEN Returns the length of a string LOWER Converts a string to lower-case LTRIM Removes leading spaces from a string NCHAR Returns the Unicode character based on the number code PATINDEX Returns the position of a pattern in a string QUOTENAME Returns a Unicode string with delimiters added to make the string a valid SQL Server delimited identifier REPLACE Replaces all occurrences of a substring within a string, with a new substring REPLICATE Repeats a string a specified number of times REVERSE Reverses a string and returns the result RIGHT Extracts a number of characters from a string (starting from right) RTRIM Removes trailing spaces from a string SOUNDEX Returns a four-character code to evaluate the similarity of two strings SPACE Returns a string of the specified number of space characters STR Returns a number as string STUFF Deletes a part of a string and then inserts another part into the string, starting at a specified position SUBSTRING Extracts some characters from a string TRANSLATE Returns the string from the first argument after the characters specified in the second argument are translated into the characters specified in the third argument. TRIM Removes leading and trailing spaces (or other specified characters) from a string UNICODE Returns the Unicode value for the first character of the input expression UPPER Converts a string to upper-case</p>
<p>–SQL Server Math/Numeric Functions Function Description ABS Returns the absolute value of a number ACOS Returns the arc cosine of a number ASIN Returns the arc sine of a number ATAN Returns the arc tangent of a number ATN2 Returns the arc tangent of two numbers AVG Returns the average value of an expression CEILING Returns the smallest integer value that is &gt;= a number COUNT Returns the number of records returned by a select query COS Returns the cosine of a number COT Returns the cotangent of a number DEGREES Converts a value in radians to degrees EXP Returns e raised to the power of a specified number FLOOR Returns the largest integer value that is &lt;= to a number LOG Returns the natural logarithm of a number, or the logarithm of a number to a specified base LOG10 Returns the natural logarithm of a number to base 10 MAX Returns the maximum value in a set of values MIN Returns the minimum value in a set of values PI Returns the value of PI POWER Returns the value of a number raised to the power of another number RADIANS Converts a degree value into radians RAND Returns a random number ROUND Rounds a number to a specified number of decimal places SIGN Returns the sign of a number SIN Returns the sine of a number SQRT Returns the square root of a number SQUARE Returns the square of a number SUM Calculates the sum of a set of values TAN Returns the tangent of a number</p>
<p>–SQL Server Date Functions Function Description CURRENT_TIMESTAMP Returns the current date and time DATEADD Adds a time/date interval to a date and then returns the date DATEDIFF Returns the difference between two dates DATEFROMPARTS Returns a date from the specified parts (year, month, and day values) DATENAME Returns a specified part of a date (as string) DATEPART Returns a specified part of a date (as integer) DAY Returns the day of the month for a specified date GETDATE Returns the current database system date and time GETUTCDATE Returns the current database system UTC date and time ISDATE Checks an expression and returns 1 if it is a valid date, otherwise 0 MONTH Returns the month part for a specified date (a number from 1 to 12) SYSDATETIME Returns the date and time of the SQL Server YEAR Returns the year part for a specified date</p>
<p>–SQL Server Advanced Functions Function Description CAST Converts a value (of any type) into a specified datatype COALESCE Returns the first non-null value in a list CONVERT Converts a value (of any type) into a specified datatype CURRENT_USER Returns the name of the current user in the SQL Server database IIF Returns a value if a condition is TRUE, or another value if a condition is FALSE ISNULL Return a specified value if the expression is NULL, otherwise return the expression ISNUMERIC Tests whether an expression is numeric NULLIF Returns NULL if two expressions are equal SESSION_USER Returns the name of the current user in the SQL Server database SESSIONPROPERTY Returns the session settings for a specified option SYSTEM_USER Returns the login name for the current user USER_NAME Returns the database user name based on the specified id</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">ADDITIONAL RESOURCES - MySQL Functions <a href="https://www.w3schools.com/sql/sql_ref_mysql.asp" class="uri">https://www.w3schools.com/sql/sql_ref_mysql.asp</a></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">–MySQL String Functions Function Description ASCII Returns the ASCII value for the specific character CHAR_LENGTH Returns the length of a string (in characters) CHARACTER_LENGTH Returns the length of a string (in characters) CONCAT Adds two or more expressions together CONCAT_WS Adds two or more expressions together with a separator FIELD Returns the index position of a value in a list of values FIND_IN_SET Returns the position of a string within a list of strings FORMAT Formats a number to a format like “#,###,###.##”, rounded to a specified number of decimal places INSERT Inserts a string within a string at the specified position and for a certain number of characters INSTR Returns the position of the first occurrence of a string in another string LCASE Converts a string to lower-case LEFT Extracts a number of characters from a string (starting from left) LENGTH Returns the length of a string (in bytes) LOCATE Returns the position of the first occurrence of a substring in a string LOWER Converts a string to lower-case LPAD Left-pads a string with another string, to a certain length LTRIM Removes leading spaces from a string MID Extracts a substring from a string (starting at any position) POSITION Returns the position of the first occurrence of a substring in a string REPEAT Repeats a string as many times as specified REPLACE Replaces all occurrences of a substring within a string, with a new substring REVERSE Reverses a string and returns the result RIGHT Extracts a number of characters from a string (starting from right) RPAD Right-pads a string with another string, to a certain length RTRIM Removes trailing spaces from a string SPACE Returns a string of the specified number of space characters STRCMP Compares two strings SUBSTR Extracts a substring from a string (starting at any position) SUBSTRING Extracts a substring from a string (starting at any position) SUBSTRING_INDEX Returns a substring of a string before a specified number of delimiter occurs TRIM Removes leading and trailing spaces from a string UCASE Converts a string to upper-case UPPER Converts a string to upper-case</td>
</tr>
<tr class="even">
<td style="text-align: left;">–MySQL Numeric Functions Function Description ABS Returns the absolute value of a number ACOS Returns the arc cosine of a number ASIN Returns the arc sine of a number ATAN Returns the arc tangent of one or two numbers ATAN2 Returns the arc tangent of two numbers AVG Returns the average value of an expression CEIL Returns the smallest integer value that is &gt;= to a number CEILING Returns the smallest integer value that is &gt;= to a number COS Returns the cosine of a number COT Returns the cotangent of a number COUNT Returns the number of records returned by a select query DEGREES Converts a value in radians to degrees DIV Used for integer division EXP Returns e raised to the power of a specified number FLOOR Returns the largest integer value that is &lt;= to a number GREATEST Returns the greatest value of the list of arguments LEAST Returns the smallest value of the list of arguments LN Returns the natural logarithm of a number LOG Returns the natural logarithm of a number, or the logarithm of a number to a specified base LOG10 Returns the natural logarithm of a number to base 10 LOG2 Returns the natural logarithm of a number to base 2 MAX Returns the maximum value in a set of values MIN Returns the minimum value in a set of values MOD Returns the remainder of a number divided by another number PI Returns the value of PI POW Returns the value of a number raised to the power of another number POWER Returns the value of a number raised to the power of another number RADIANS Converts a degree value into radians RAND Returns a random number ROUND Rounds a number to a specified number of decimal places SIGN Returns the sign of a number SIN Returns the sine of a number SQRT Returns the square root of a number SUM Calculates the sum of a set of values TAN Returns the tangent of a number TRUNCATE Truncates a number to the specified number of decimal places</td>
</tr>
<tr class="odd">
<td style="text-align: left;">–MySQL Date Functions Function Description ADDDATE Adds a time/date interval to a date and then returns the date ADDTIME Adds a time interval to a time/datetime and then returns the time/datetime CURDATE Returns the current date CURRENT_DATE Returns the current date CURRENT_TIME Returns the current time CURRENT_TIMESTAMP Returns the current date and time CURTIME Returns the current time DATE Extracts the date part from a datetime expression DATEDIFF Returns the number of days between two date values DATE_ADD Adds a time/date interval to a date and then returns the date DATE_FORMAT Formats a date DATE_SUB Subtracts a time/date interval from a date and then returns the date DAY Returns the day of the month for a given date DAYNAME Returns the weekday name for a given date DAYOFMONTH Returns the day of the month for a given date DAYOFWEEK Returns the weekday index for a given date DAYOFYEAR Returns the day of the year for a given date EXTRACT Extracts a part from a given date FROM_DAYS Returns a date from a numeric datevalue HOUR Returns the hour part for a given date LAST_DAY Extracts the last day of the month for a given date LOCALTIME Returns the current date and time LOCALTIMESTAMP Returns the current date and time MAKEDATE Creates and returns a date based on a year and a number of days value MAKETIME Creates and returns a time based on an hour, minute, and second value MICROSECOND Returns the microsecond part of a time/datetime MINUTE Returns the minute part of a time/datetime MONTH Returns the month part for a given date MONTHNAME Returns the name of the month for a given date NOW Returns the current date and time PERIOD_ADD Adds a specified number of months to a period PERIOD_DIFF Returns the difference between two periods QUARTER Returns the quarter of the year for a given date value SECOND Returns the seconds part of a time/datetime SEC_TO_TIME Returns a time value based on the specified seconds STR_TO_DATE Returns a date based on a string and a format SUBDATE Subtracts a time/date interval from a date and then returns the date SUBTIME Subtracts a time interval from a datetime and then returns the time/datetime SYSDATE Returns the current date and time TIME Extracts the time part from a given time/datetime TIME_FORMAT Formats a time by a specified format TIME_TO_SEC Converts a time value into seconds TIMEDIFF Returns the difference between two time/datetime expressions TIMESTAMP Returns a datetime value based on a date or datetime value TO_DAYS Returns the number of days between a date and date “0000-00-00” WEEK Returns the week number for a given date WEEKDAY Returns the weekday number for a given date WEEKOFYEAR Returns the week number for a given date YEAR Returns the year part for a given date YEARWEEK Returns the year and week number for a given date</td>
</tr>
<tr class="even">
<td style="text-align: left;">–MySQL Advanced Functions Function Description BIN Returns a binary representation of a number BINARY Converts a value to a binary string CASE Goes through conditions and return a value when the first condition is met CAST Converts a value (of any type) into a specified datatype COALESCE Returns the first non-null value in a list CONNECTION_ID Returns the unique connection ID for the current connection CONV Converts a number from one numeric base system to another CONVERT Converts a value into the specified datatype or character set CURRENT_USER Returns the user name and host name for the MySQL account that the server used to authenticate the current client DATABASE Returns the name of the current database IF Returns a value if a condition is TRUE, or another value if a condition is FALSE IFNULL Return a specified value if the expression is NULL, otherwise return the expression ISNULL Returns 1 or 0 depending on whether an expression is NULL LAST_INSERT_ID Returns the AUTO_INCREMENT id of the last row that has been inserted or updated in a table NULLIF Compares two expressions and returns NULL if they are equal. Otherwise, the first expression is returned SESSION_USER Returns the current MySQL user name and host name SYSTEM_USER Returns the current MySQL user name and host name USER Returns the current MySQL user name and host name VERSION Returns the current version of the MySQL database</td>
</tr>
</tbody>
</table>
<p>ADDITIONAL RESOURCES - CTE EXPLAINED</p>
<p>–Basic structure, layman’s terms. A Common Table Expression (CTE) can be used many ways, but for the most basic use, think of it as a sub-query, or temp-query that you can reference within your primary query.</p>
<p>In Microsoft Power Query (Excel/PowerBI), this would be akin to pulling in a table as “connection only”, doing some transformations within that connection only table, and then referencing or merging that connection only table into your final results. But unlike PowerQuery tables, you can do all the transformations in a few lines of code, without pulling in millions of rows of data before transformations.</p>
<p>//Start Example CTE –CTE PRECEDING MAIN QUERY, This is you sub-query, or “connection only” query, which you will reference in your final query(s). –CTE can be used to get a RowNum as below, MAX, AVERAGE, SUM, etc.</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>WITH CTE_TableNameYouAssign AS ( SELECT column1 column2 column3 ROW_NUMBER() OVER (PARTITION BY column3 ORDER BY column1 DESC) AS RowNum</p>
<p>FROM TableNameYouAreReferencing AS aliashere WHERE columnwhatever = ‘some condition’ )</p>
<p>–MAIN QUERY STARTS HERE, Now you will build the original query you wanted, and pull in the results of the CTE (often just the one column you needed). –Select Statements</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>SELECT DISTINCT a.column1 a.column2 a.column3 a.column4 a.column5 b.column – from CTE above, uses table join alias below, this is the part that confused me.</p>
<p>–From, Join Where(s), Order By</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>FROM primarytable AS a LEFT OUTER JOIN CTE_TableNameYouAssign AS b ON a.columnkey=b.columnkey WHERE a.column1 = ‘some condition’ AND a.column2 = ‘some condition’ ORDER BY columnwhatever;</p>
<p>//End Example CTE</p>
<p>–**–An example I’ve actually used with a CTE, Treasurer_Warrants //Begin example</p>
<p>–CTE PRECEDING MAIN QUERY</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>WITH CTE_DescrHeader AS ( SELECT dh.Id, dh.BegEffDate, dh.TranId, dh.RevObjId, dh.DescrHeaderType, dh.DisplayDescr, ROW_NUMBER() OVER (PARTITION BY dh.RevObjId ORDER BY dh.BegEffDate DESC) AS RowNum FROM DescrHeader AS dh WHERE dh.EffStatus = ‘A’ )</p>
<p>–MAIN QUERY STARTS HERE</p>
<p>–Select Statements</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>SELECT DISTINCT –Demographics LTRIM(RTRIM(kcv.ain)) AS [AIN], LTRIM(RTRIM(kcv.pin)) AS [PIN], LTRIM(RTRIM(pb.OwnerName1)) AS [Owner], LTRIM(RTRIM(pb.OwnerName2)) AS [AltOwner], LTRIM(RTRIM(kcv.AttentionLine)) AS [Comm_Attn], LTRIM(RTRIM(kcv.MailingAddress)) AS [MailingAddress], LTRIM(RTRIM(kcv.MailingCityStZip)) AS [Mailing_CSZ], LTRIM(RTRIM(pb.OwnerCountry)) AS [OwnerCountry], LTRIM(RTRIM(kcv.SitusAddress)) AS [SitusAddress], LTRIM(RTRIM(kcv.DisplayDescr)) AS [LegalDescription], dd.DisplayDescr AS [ParcelBase_LegalDesc], –Amounts (incomplete, still searching for these figures) del.TaxAmount AS [TaxDue], del.PenAmount AS [Penalty], del.IntAmount AS [Interest], del.FeeAmount AS [Fees], –Year, Vin, Make, if applicable i.year_built AS [YearBuilt], LTRIM(RTRIM(mh.mh_serial_num)) AS [VIN], LTRIM(RTRIM(ct.tbl_element_desc)) AS [Make]</p>
<p>–From tables/joined tables</p>
<p>FROM KCv_PARCELMASTER1 AS kcv LEFT OUTER JOIN parcel_base_data AS pb ON kcv.lrsn=pb.lrsn LEFT OUTER JOIN CTE_DescrHeader AS dd ON pb.lrsn=dd.RevObjId LEFT OUTER JOIN manuf_housing AS mh ON kcv.lrsn=mh.lrsn LEFT OUTER JOIN codes_table AS ct ON mh.mh_make=ct.tbl_element AND ct.tbl_type_code=‘mhmake’ LEFT OUTER JOIN improvements AS i ON mh.lrsn=i.lrsn AND mh.extension=i.extension LEFT OUTER JOIN eGovDelq_T AS del ON kcv.lrsn=del.RevObjId</p>
<p>–Where conditions WHERE kcv.EffStatus=‘A’ AND pb.status=‘A’ AND mh.status=‘A’ AND i.status=‘A’ AND dd.RowNum = 1 AND i.improvement_id=‘M’ AND kcv.pin NOT LIKE ‘GENERAL PARCEL’ AND kcv.pin LIKE ‘M%’ OR kcv.pin LIKE ‘L%’ OR kcv.pin LIKE ‘G%’ OR kcv.pin LIKE ‘E%’ OR (kcv.pin LIKE ‘R%’ AND kcv.DisplayDescr LIKE ‘%Golden Spike%’) OR (kcv.pin LIKE ‘U%’ AND kcv.ClassCD=‘010 Operating Property’) OR (kcv.pin LIKE ‘%’ AND kcv.DisplayDescr LIKE ‘%PP On Real%’)</p>
<p>ORDER BY [PIN]; //End example</p>
<p><code>{sql eval=FALSE, include=TRUE}</code></p>
<p>–**–Microsoft SQL Server 2022: WITH common_table_expression (Transact-SQL) <a href="https://learn.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver16" class="uri">https://learn.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver16</a> Specifies a temporary named result set, known as a common table expression (CTE). This is derived from a simple query and defined within the execution scope of a single SELECT, INSERT, UPDATE, DELETE or MERGE statement. This clause can also be used in a CREATE VIEW statement as part of its defining SELECT statement. A common table expression can include references to itself. This is referred to as a recursive common table expression.</p>
<p>The following guidelines apply to nonrecursive common table expressions. For guidelines that apply to recursive common table expressions, see Guidelines for Defining and Using Recursive Common Table Expressions that follows.</p>
<p>A CTE must be followed by a single SELECT, INSERT, UPDATE, or DELETE statement that references some or all the CTE columns. A CTE can also be specified in a CREATE VIEW statement as part of the defining SELECT statement of the view. Multiple CTE query definitions can be defined in a nonrecursive CTE. The definitions must be combined by one of these set operators: UNION ALL, UNION, INTERSECT, or EXCEPT. A CTE can reference itself and previously defined CTEs in the same WITH clause. Forward referencing isn’t allowed. Specifying more than one WITH clause in a CTE isn’t allowed. For example, if a CTE_query_definition contains a subquery, that subquery can’t contain a nested WITH clause that defines another CTE.</p>
<p>The following clauses can’t be used in the CTE_query_definition:</p>
<p>ORDER BY (except when a TOP clause is specified) INTO OPTION clause with query hints FOR BROWSE</p>
<p>When a CTE is used in a statement that is part of a batch, the statement before it must be followed by a semicolon. A query referencing a CTE can be used to define a cursor. Tables on remote servers can be referenced in the CTE. When executing a CTE, any hints that reference a CTE may conflict with other hints that are discovered when the CTE accesses its underlying tables, in the same manner as hints that reference views in queries. When this occurs, the query returns an error.</p>
<p>–**– SQLSHACK SQL Server Common Table Expressions (CTE) <a href="https://www.sqlshack.com/sql-server-common-table-expressions-cte/" class="uri">https://www.sqlshack.com/sql-server-common-table-expressions-cte/</a> A Common Table Expression, also called as CTE in short form, is a temporary named result set that you can reference within a SELECT, INSERT, UPDATE, or DELETE statement. The CTE can also be used in a View.</p>
<p>EXPLANATION: The CTE query starts with a ?With? and is followed by the Expression Name. We will be using this expression name in our select query to display the result of our CTE Query and be writing our CTE query definition. To view the CTE result we use a Select query with the CTE expression name.</p>
<p>-EXAMPLE: WITH expression_name [ ( column_name [,…n] ) ] AS ( CTE_query_definition ) Select [Column1,Column2,Column3 ?..] from expression_name</p>
<p>–Or</p>
<p>WITH expression_name [ ( column_name [,…n] ) ] AS ( CTE_query_definition ) Select * from expression_name</p>
<p>–CTE with Union All In order to display the result from start date to end date one by one as recursive, we use a Union All to increment RowNo, to add the day one by one till the condition satisfied the date range, in order to stop the recursion we need set some condition. In this example, we repeat the recursion to display our records until the date is less than or equal to the end date.</p>
<p>-EXAMPLE declare <span class="citation" data-cites="startDate">@startDate</span> datetime,<br>
<span class="citation" data-cites="endDate">@endDate</span> datetime;</p>
<p>select <span class="citation" data-cites="startDate">@startDate</span> = getdate(),<br>
<span class="citation" data-cites="endDate">@endDate</span> = getdate()+16;<br>
– select <span class="citation" data-cites="sDate">@sDate</span> StartDate,<span class="citation" data-cites="eDate">@eDate</span> EndDate<br>
;with myCTE as<br>
(<br>
select 1 as ROWNO,<span class="citation" data-cites="startDate">@startDate</span> StartDate,‘W -’+convert(varchar(2),<br>
DATEPART( wk, <span class="citation" data-cites="startDate">@startDate</span>))+’ / D (‘+convert(varchar(2),<span class="citation" data-cites="startDate">@startDate</span>,106)+’)’ as ‘WeekNumber’<br>
union all<br>
select ROWNO+1 ,dateadd(DAY, 1, StartDate) ,<br>
‘W -’+convert(varchar(2),DATEPART( wk, StartDate))+’ / D (‘+convert(varchar(2),<br>
dateadd(DAY, 1, StartDate),106)+’)’ as ‘WeekNumber’<br>
FROM myCTE<br>
WHERE dateadd(DAY, 1, StartDate)&lt;= <span class="citation" data-cites="endDate">@endDate</span><br>
)<br>
select ROWNO,Convert(varchar(10),StartDate,105) as StartDate ,WeekNumber from myCTE</p>
<p>–ANOTHER EXAMPLE FROM SQL SERVER TUTORIAL <a href="https://www.sqlservertutorial.net/sql-server-basics/sql-server-cte/" class="uri">https://www.sqlservertutorial.net/sql-server-basics/sql-server-cte/</a></p>
<p>WITH cte_sales AS ( SELECT staff_id, COUNT(*) order_count<br>
FROM sales.orders WHERE YEAR(order_date) = 2018 GROUP BY staff_id )</p>
<p>SELECT AVG(order_count) average_orders_by_staff FROM cte_sales;</p>
<p>–MORE EXAMPLES AT MS SQL TIPS <a href="https://www.mssqltips.com/sqlservertip/6861/cte-in-sql-server-examples/" class="uri">https://www.mssqltips.com/sqlservertip/6861/cte-in-sql-server-examples/</a> -EX 1</p>
<p>WITH Sum_OrderQuantity_CTE AS ( SELECT ProductKey ,EnglishMonthName ,SUM(OrderQuantity) AS TotalOrdersByMonth FROM [dbo].[FactInternetSales] fs INNER JOIN [dbo].[DimDate] dd ON dd.DateKey = fs.OrderDateKey GROUP BY ProductKey, EnglishMonthName</p>
<p>) SELECT ProductKey, AVG(TotalOrdersByMonth) AS ‘Average Total Orders By Month’ FROM Sum_OrderQuantity_CTE GROUP BY ProductKey ORDER BY ProductKey</p>
<p>-EX 2 WITH Simple_CTE AS ( SELECT dd.CalendarYear ,fs.OrderDateKey ,fs.ProductKey ,fs.OrderQuantity * fs.UnitPrice AS TotalSale ,dc.FirstName ,dc.LastName FROM [dbo].[FactInternetSales] fs INNER JOIN [dbo].[DimCustomer] dc ON dc.CustomerKey = fs.CustomerKey INNER JOIN [dbo].[DimDate] dd ON dd.DateKey = fs.OrderDateKey ) SELECT * FROM Simple_CTE</p>
<hr>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: left;">ADDITIONAL RESOURCES -</td>
</tr>
</tbody>
</table>
<p>*/</p>
</section>
<section id="format" class="level3">
<h3 class="anchored" data-anchor-id="format">Format</h3>
<p><img src="Images/FORMAT1.jpg" class="img-fluid"></p>
<p><img src="Images/FORMAT2.jpg" class="img-fluid"></p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>