---
title: "QMD Documentation Quick Reference Library"
format: html
editor_options:
  markdown:
    wrap: 72
---

# Creating .qmd Documentation

This is intended to serve as a basic reference for .qmd documents

Most start with a YAML (that is the title at the top of this page in between two sets of three dahes).

## Code Chunks - FYI
When creating .qmd documents you can use the following to create code chunks. Eval (evaluation) means you want the code chunk to actually run and display its results in the final document, 
while include means that you want to display the code chunk (false would mean to hide it) in the final document.

```markdown
```{r eval=FALSE, include=TRUE} code goes between this and the three end quotes, but each on it's own line.```
```{SQL eval=FALSE, include=TRUE} code ```
```{python eval=FALSE, include=TRUE} code ```
```

# Links
This is an example of a link format
`[Link text](https://example.com)`



# Sample Section Header

This is text, usually with a space between this and the header

## SampleSubHeader

This is text, usually with a space between this and the header

-   List
-   List
    -   SubList indented
    -   SubList indented

### SampleSubSubHeader

This is text, usually with a space between this and the header

#### SampleSubSubSubHeader

This is text, usually with a space between this and the header


This is a code chuck
```{python eval=FALSE, include=TRUE} 

# THIS IS THE COMMENT

# if you haven't already, open a Terminal and 
# pip install datetime

import datetime

# THIS IS ALSO A COMMENT

the_month = datetime.datetime.now().month
the_day = datetime.datetime.now().day
the_year = datetime.datetime.now().year


# Get the current and next year
current_year = datetime.datetime.now().year
next_year = current_year + 1


print(the_month)


print(the_day)


print(the_year)


print(current_year)


print(next_year)


print(datetime.datetime.now())


print(the_month,the_day,the_year)


print(f"{the_month}/{the_day}/{the_year}")

```





