SELECT R.RO_ID, R.RO_PIN, R.RO_AIN, SW.BEGTAXYEAR, sw.id, sw.effstatus, SW.SAID, SW.AMOUNT

FROM CADINV CI

left outer JOIN SW_SCB_V SW ON SW.REVOBJID=CI.REVOBJID and sw.effstatus <> 'I'

JOIN REVOBJKC_V R ON CI.REVOBJID=R.RO_ID

WHERE CADINVCTRLID=229

ORDER BY 

--R.RO_PIN

SW.AMOUNT, R.RO_PIN
