

AND (parcel.DisplayName NOT LIKE 'STIMSON LUMBER CO%'
AND parcel.DisplayName NOT LIKE 'MOLPUS%'
AND parcel.DisplayName NOT LIKE 'JACKSON TIMB%'
AND parcel.DisplayName NOT LIKE 'NANDDIC CRYSTAL%'
AND parcel.DisplayName NOT LIKE 'JAMESTOWN FANDEST%'
AND parcel.DisplayName NOT LIKE 'CARMONA TRISTAR%'
AND parcel.DisplayName NOT LIKE 'HANCOCK TIMER%'
AND parcel.DisplayName NOT LIKE 'JOHN HANCOCK LIFE%'
AND parcel.DisplayName NOT LIKE 'BOSTON TIMBER%'
AND parcel.DisplayName NOT LIKE 'SYSTEM GLOBAL TIMB%'
AND parcel.DisplayName NOT LIKE 'GOLDEN POND TIMB%'
AND parcel.DisplayName NOT LIKE 'MANUELIFE%'
AND parcel.DisplayName NOT LIKE 'BENNETT LUMBER%'
AND parcel.DisplayName NOT LIKE 'BUELL BROTHERS%'
AND parcel.DisplayName NOT LIKE 'F & G TIMBER%'
AND parcel.DisplayName NOT LIKE 'POTLATCH%'
AND parcel.DisplayName NOT LIKE 'IFG%'
AND parcel.DisplayName NOT LIKE 'INLAND EMPIRE%'
AND parcel.DisplayName NOT LIKE 'INLAND FANDEST%'
AND parcel.DisplayName NOT LIKE 'JT HOLDINGS%'
AND parcel.DisplayName NOT LIKE 'KOOTENAI LAND%'
AND parcel.DisplayName NOT LIKE 'KOOTENAI PROPERTIES%'
AND parcel.DisplayName NOT LIKE 'KROETCH%'
AND parcel.DisplayName NOT LIKE 'MAGNUSON PROP%'
AND parcel.DisplayName NOT LIKE 'MAGNUSON MICA BAY%'
AND parcel.DisplayName NOT LIKE 'MICA BAY LAND DEV%'
AND parcel.DisplayName NOT LIKE 'PRIEST RIVER LAND%'
AND parcel.DisplayName NOT LIKE 'RILEY CREEK LUMB%')
